** Proof of Sum Rule
Proof of (d/dx) [f(x) + g(x)] = (d/dx) f(x) + (d/dx) g(x) from the definition.

We can use the definition of the derivative:

$\frac{d}{dx} f(x) =	\lim_{x\to 0} \frac{f(x+d)-f(x)}{d}$

Therefore, $\frac{d}{dx} [f(x) + g(x)] =	\lim_{x\to 0} \frac{[f(x+d)+ g(x+d)] - [f(x)+g(x)]}{d}$

Let's just rearrange this a little: $\frac{[f(x+d) - f(x) ] + [g(x+d) + g(x)]}{d}$, and then $\frac{f(x+d) - f(x)}{d} + \frac{g(x+d) + g(x)}{d}$.

But this is just our original definition.

** Proof of Chain Rule
Prime notation shows the mechanics clearer, Leibniz notation the concept.
Prime notation: $(f o g)' (x) = f'(g(x)) \cdot g'(x)$

And from Leibniz: $\frac{dy}{dx} = \frac{dy}{du} \frac{du}{dx}$

Since we are asking about a rate of change, relative to another rate of change,
which is relative to x, it make sense that any change to x gets amplified as it
ricochets through our little machine.

dy/dx is the result of a function. It is f(x + dx) - f(x) by (x + dx).
Actually, I suppose they are both infinitesimals, but the dy infinitesimal is
obtained through a function.

The proof is a straight-up algebraic "chain" of reasoning.

*** Part A
Remember $\Delta y = f(a + \Delta x) - f(x)$, and as $\Delta x \rightarrow 0$ we have $\Delta y/\Delta x = f'(a)$.

Let's make $\epsilon$ equal the difference between our [[https://en.wikipedia.org/wiki/Difference_quotient][ difference quotient ]] and the derivative.

As $\Delta x \rightarrow 0$, we have $\epsilon = (\frac{\Delta y}{\Delta x} - f'(a)) = f'(a) - f'(a) = 0$.

This lets us do $\epsilon = (\Delta y/\Delta x - f'(a) \Rightarrow \Delta y = f'(a) \Delta x + \epsilon \Delta x$

To make $\epsilon$ differentiable, we let it go to 0 when $\Delta x = 0$.
$\Delta y = f'(a) \Delta x + \epsilon \Delta x$ where $\epsilon \to 0$ as $\Delta x \to 0$.

This is a little obscurantist, because f'(a) and our difference quotient are exactly
the same thing.

*** Part B
The stage is now set. Suppose $u = g(x)$ is differentiable at a, and $y = f(u)$ at 
the same location, but we'll say $b = g(a)$. $f(g(a))$, or $f(b)$.

Then, $\Delta u = g'(a) \Delta x + \epsilon \Delta x$. And this equals $[g'(a) + \epsilon](\Delta x)$.

And, $\Delta y = f'(b) (\Delta u) + \epsilon (\Delta u)$. And, $= [f'(b) + \epsilon](\Delta u)$.

Substituting the first result into the second, we have
$\Delta y = [f'(b) + \epsilon] [g'(a) + \epsilon](\Delta x)$.
Now as $\Delta x \to 0$, so does $\Delta u$, and thus both our $\epsilon \to 0$.
Therefore $\frac{dy}{dx} = (\Delta x \to 0) \frac{(\Delta y)}{(\Delta x)} = (lim_{\Delta x \to 0}) [f'(b) + \epsilon] [g'(a) + \epsilon] = f'(b) g'(a) = f'(g(a)) g'(a)$.

*** This proves the Chain Rule.
We found a way to represent the change in y as the result of the derivative of
a point plus a small change, multiplied by the change in x - to show a change in
y in reference to an already-established rate.

This somewhat sneaky characterization let us see more clearly what we could not
before - that the change in y relative to the change in x, when functions are composed,
depends on the derivatives of both functions.

$\epsilon = \frac{\Delta y)}{\Delta x} - \frac{\Delta y}{\Delta x}$

$\Delta x \epsilon = \Delta y - (\Delta x)[\frac{(\Delta y}{(\Delta x)}]$

$\Delta y = (\Delta x)[\frac{(\Delta y}{(\Delta x)}] + (\Delta x) \epsilon$

$\Delta y = (\Delta x)[\frac{(\Delta y}{(\Delta x)} + \epsilon]$

$(\frac{\Delta y)}{(\Delta x)} = (\frac{\Delta y)}{(\Delta u)} \frac{(\Delta u}{(\Delta x)}$

But since we are not using infinitesimals, and we use the Leibniz notation because 
sometimes it shows these relations more clearly, we cannot cancel out $(\Delta u)$.
Rather, these represent the results of taking the limit, and given any actual
functions f and g, we would have to apply our usual method of adding an h and
doing algebra, and so on.

So we can treat $\Delta x$ and others above as algebraic quantities, but to actually
find the derivative we then must find the limit as $\Delta x \to 0$. We can work with them
algebraically before taking the limit, but not use them to actually find the derivative.

*** Sal Khan's Method
Is, naturally, the easiest.

$\frac{dy}{dx} = lim_{\Delta x \to 0} \frac{\Delta y}{\Delta x}$ 

If we multiply the last part, we get:
$lim_{\Delta x \to 0} \frac{\Delta y}{\Delta x} \frac{\Delta u}{\Delta u} = lim_{\Delta x \to 0} \frac{\Delta y}{\Delta u} \frac{\Delta u}{\Delta x}$ 


But we're allowed to take the limits separately.

$lim_{\Delta x \to 0} \frac{\Delta y}{\Delta u} \frac{\Delta u}{\Delta x} = lim_{\Delta x \to 0} \frac{\Delta y}{\Delta u} \cdot lim_{\Delta x \to 0} \frac{\Delta u}{\Delta x}$ 


And we can change the first x to a u, because as x approaches 0, so does the function of x:

$lim_{\Delta x \to 0} \frac{\Delta y}{\Delta u} \frac{\Delta u}{\Delta x} = lim_{\Delta u \to 0} \frac{\Delta y}{\Delta u} \cdot lim_{\Delta x \to 0} \frac{\Delta u}{\Delta x}$ 


And naturally that's $\frac{dy}{du} \frac{du}{dx}$.

(although so far as I can see, when we say u approaches 0 when x does, we are kind of cheating, because we are saying u is 0 in the first but not in the second).
** Back Propagation
I found the video's explanation confusing, but the calculus is very simple.

The chain rule is like using silverware at a fine dining experience: start from the outside and work in.

For instance $x^2$ can be thought of as $(x)^2$. Take the derivative of the outer function, $2(x)$, then multiply by the derivative of the inner function, which is $x$ with a derivative of $1$: $2(x) * 1 = 2x$.

\begin{center}
\begin{tabular}{ c c }
 Outer & x^4 \\ 
     & (x^2)^2 \\  
 to & 2 x^2 \cdot (x^2)' \\
    &  2 \cdot 2x \cdot x' \\
 Inner & 2 \cdot 2x \cdot x = 4x^3
\end{tabular}
\end{center}

To take a partial derivative, you take one variable at a time, and treat the other variables like constants. For instance, if you had $2x$, you could split it into $x + x$ and differentiate each separately.

The partial derivative asks "how much did each part contribute?" Here each part contributed $1$.

Our cost function is $J = \sum \frac{1}{2}(y - \hat{y})^2$, and we want to take its derivative so we know how to improve our weights.

We can add it all up later, so we ignore the summation. The derivative of $\frac{1}{2}(y - \hat{y})^2$ is just $ 2 * \frac{1}{2}(y - \hat{y})$ times the derivative of the inner function.

Clearly the 2 and 0.5 multiply out, leaving us with $(y - \hat{y})$ for the first outer function.

For the inner function, $y$ is a constant and disappears. If we separate the negative sign like $(-1) \hat{y}$, it won't disappear but the math is easier.

To differentiate $\hat{y}$, we look at the actual function, which is $\sigma(w2 * x)$, where $x$ is the example that W2 gets. So we differentiate $\sigma$, then differentiate the inner function. Let's differentiate $\sigma$ in a second or two.

At this point our entire derivative is just: $(y - \hat{y}) \cdot \sigma'(w2 * x) \cdot (w2 * x)'$, where we haven't yet figured out the last term.

The last term is easy though. $w2$ is our variable, and $x$ is a constant. It is like normal calculus, where you have to differentiate $2x$ or something, and the derivative is just $2$.

Here the derivative is $x$, which is the result of $\sigma(w1 * x)$, which is more math to do, but we don't have to do any calculus on it, it is just straight multiplication.

We now have $(y - \hat{y}) \cdot \sigma'(w2 * x) \cdot x$, and all we have to do is differentiate $\sigma$.

You can apply the product rule or the quotient rule, whichever you like.


To take this derivative, rewrite as $(1 + e^{-z})^{-1}$, and apply the power
rule to get $-(1 + e^{-z})^{-2}$, but then we must apply the product rule to get
$-(1 + e^{-z})^{-2})(\frac{d}{z} 1 + e^{-z})$. Which equals:

$-(1 + e^{-z})^{-2})(\frac{d}{dz}(1 + e^{-z})) = -(1 + e^{-z})^{-2})(-1)(e^{-z}))$

And:
$\frac{e^{-z}}{(1 + e^{-z})^{2}}$. 

If you do a lot of algebra there, you can also write this as $\sigma(x) \cdot (1 - \sigma(x))$.
That is more easily seen if you work backwards.

$\frac{1}{1 + e^{-z}}(1 - \frac{1}{1 + e^{-z}}) = \frac{1}{1 + e^{-z}} - \frac{1}{( 1 + e^{-z})^2} = \frac{1 + e^{-z} - 1}{( 1 + e^{-z})^2}$


Anyway, we have $(-1)(y - \hat{y}) \cdot \frac{e^{-z}}{(1 + e^{-z})^{2}} \cdot (x_2)$. The point is that the big three differentiations here are not very hard to do.

To differentiate the other weights, we do all the same steps, but we treat w2 as a constant.

We start out the same until we get to: $(y - \hat{y}) \cdot \sigma'(w2 * x) \cdot (w2 * x)'$. Here, we treat $w2$ as the constant, but $x$ depends on $w1$, which is what we are interested in now.

Hence the derivative now is $w2 \cdot x'$, which is $\sigma(w1 * x_1)$ (the $x_1$ is the $x$ that w1 sees, not the one that w2 sees after going through w1 and $\sigma$).

Differentiating $\sigma(w1 * x_1)$ works out the same as last time, just with a different $z$ this time.

Our final derivative now is $(-1)(y - \hat{y}) \cdot \frac{e^{-z}}{(1 + e^{-z})^{2}} \cdot (w2) \cdot \frac{e^{-z}}{(1 + e^{-z})^{2}} \cdot x_1$

*** Group Them
The math is actually pretty simple, if you understand the chain rule, product or quotient rule, and the gist of partial derivatives.

We can get a little more insight into what the calculus is doing if we group things together. For instance, $(y - \hat{y})$ is the error, and $\frac{e^{-z}}{(1 + e^{-z})^{2}}$ holds w2 multipled by x (in the z) and hence shows us how much of a mistake this neuron has made.

We put them under a single notation, called "the back-propagating error, $\delta^{(3)}$."

For w1, we have to multiply again by its own $\frac{e^{-z}}{(1 + e^{-z})^{2}}$. We multiply each error by the size of the neuron, and of its child neuron!

I suppose this means earlier weights get adjusted more; they are responsible for the faults of their children!

When we combine $\delta^{(3)}$ with that whole $w2 \cdot \frac{e^{-z}}{(1 + e^{-z})^{2}}$ bit we call it $\delta^{(2)}$.

To make this all work out with many examples, you have to flip and spin matrices a bit.
